# Reshaping ,Stacking ,Squeezing ,Unsqueezing
sometimes we will be needed to change the shape and dimmension of tensors without changing the data inside it 

In [1]:
import torch

/usr/local/python/3.12.1/lib/python3.12/site-packages/torch/_subclasses/functional_tensor.py:307: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [2]:
x = torch.tensor([1, 2, 3])
x,x.shape

(tensor([1, 2, 3]), torch.Size([3]))

In [6]:
x_reshaped = x.reshape(1, 3)
# .reshape(dimension,column_size)
# it is used to change the shape of the tensor without changing its data.
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3]]), torch.Size([1, 3]))

In [11]:
# .view() is same as .reshape but it returns a new tensor .
# also .view() points to the same memory location as the original tensor.
z = x.view(1, 3)
z[:,1]=7
z,x

(tensor([[1, 7, 3]]), tensor([1, 7, 3]))

In [16]:
stacked_x_row = torch.stack((x,x,),dim=0) 
# .stack is used to put the tensors on top of each other along a new dimension.
# also if dim = 0 it means row wise stacking and if dim = 1 it means column wise stacking.
stacked_x_row, stacked_x_row.shape

(tensor([[1, 7, 3],
         [1, 7, 3]]),
 torch.Size([2, 3]))

In [17]:
stacked_x_col = torch.stack((x,x,),dim=1)
stacked_x_col, stacked_x_col.shape

(tensor([[1, 1],
         [7, 7],
         [3, 3]]),
 torch.Size([3, 2]))

In [27]:
# squeezing is used to remove the dimensions of size 1 from the tensor.
# unsqueezing is used to add a dimension of size 1 to the tensor.
unsqueezed_x_tensor = x.unsqueeze(dim=0)
unsqueezed_x_tensor, unsqueezed_x_tensor.shape


(tensor([[1, 7, 3]]), torch.Size([1, 3]))

In [28]:
squeezed_x_tensor = unsqueezed_x_tensor.squeeze(dim=0)
squeezed_x_tensor, squeezed_x_tensor.shape

(tensor([1, 7, 3]), torch.Size([3]))

In [32]:
y = torch.rand(size=(224,224,3))

# .permute() is used to change the order of the dimensions of the tensor.
permuted_y = y.permute(2,0,1)

y.shape, permuted_y.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))