# Tensors Manipulation
here we will learn what operations we can perform on tensors 

In [1]:
import torch

/usr/local/python/3.12.1/lib/python3.12/site-packages/torch/_subclasses/functional_tensor.py:307: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [ ]:
#addition to tensors
tensors = torch.tensor([1,2,3,4,5])
tensors+10

tensor([11, 12, 13, 14, 15])

In [4]:
#multiplication to tensors
tensors*10

tensor([10, 20, 30, 40, 50])

In [5]:
#if two tensors are equal in size we can do element wise multiplication
tensors*tensors

tensor([ 1,  4,  9, 16, 25])

In [7]:
'''
we can also do matrix multiplication using @ and torch.matmul(A,B)
if A is of size (m,n) and B is of size (n,p) then the result will be of size (m,p)
and also the n and p should be equal for the multiplication to be possible
the "inner dimensions are consumed" in the multiplication
'''

'\nwe can also do matrix multiplication using @ and torch.matmul(A,B)\nif A is of size (m,n) and B is of size (n,p) then the result will be of size (m,p)\nand also the n and p should be equal for the multiplication to be possible\nthe "inner dimensions are consumed" in the multiplication\n'

In [10]:
tensors.matmul(tensors)
# It will return dot product of the two tensors and the result will be a scalar value 
# because the two tensors are of size (5,) and (5,) and the result will be of size (1,)


''' 
Rule of thumb:

* 1D × 1D → scalar (dot product)
* 2D × 2D → matrix multiplication
* 2D × 1D → matrix-vector multiplication
* Higher dimensions → batched matrix multiplication
'''

' \nRule of thumb:\n\n* 1D × 1D → scalar (dot product)\n* 2D × 2D → matrix multiplication\n* 2D × 1D → matrix-vector multiplication\n* Higher dimensions → batched matrix multiplication\n'