# What are tensors ?
A tensor is a multi-dimensional array used to store and process data in machine learning and deep learning. Scalars, vectors, and matrices are all special cases of tensors.

# Why Tensors when we have numpy and matrix ?
If matrices and NumPy arrays already exist, why did deep learning frameworks create tensors?

1. A matrix is just a special case of a tensor

Think of it like this:

Object	Dimensions
Scalar	0D
Vector	1D
Matrix	2D
Tensor	nD

Examples:

#### Scalar (0D tensor)
5
#### Vector (1D tensor)
[1, 2, 3]
#### Matrix (2D tensor)
[[1, 2],
 [3, 4]]
#### Tensor (3D tensor)
[
 [[1, 2], [3, 4]],
 [[5, 6], [7, 8]]
]

A matrix can only represent 2 dimensions, while tensors can represent any number of dimensions.

⸻

2. Real ML data is often not 2D

Suppose you have:

* 100 images
* each image is 224 × 224 pixels
* RGB channels (3)

Shape:

(100, 224, 224, 3)

This is a 4D tensor.

A matrix cannot naturally represent this.

⸻

3. Tensors can run on GPUs

NumPy arrays are mostly CPU-based.

import numpy as np
a = np.array([1,2,3])

PyTorch tensors can live on a GPU:

import torch
a = torch.tensor([1,2,3]).cuda()

GPU acceleration is one of the biggest reasons tensors are used in deep learning.

⸻

4. Automatic Differentiation (Autograd)

Neural networks need gradients.

NumPy:

import numpy as np
x = np.array(3.0)
y = x**2

NumPy doesn’t know:

\frac{dy}{dx}

PyTorch:

x = torch.tensor(3.0, requires_grad=True)
y = x**2
y.backward()
print(x.grad)

Output:

tensor(6.)

PyTorch automatically computes gradients.

This is essential for training neural networks.

⸻

5. Tensors have ML-specific operations

PyTorch tensors support:

* GPU computation
* Automatic differentiation
* Neural network operations
* Distributed training
* Mixed precision training

NumPy arrays don’t provide these features.

⸻

Simple analogy

* Matrix = a spreadsheet with rows and columns (2D only).
* NumPy array = a flexible container for numerical data.
* Tensor = a NumPy array plus GPU support, automatic gradients, and deep-learning capabilities.

You can think of a PyTorch tensor as:

Tensor ≈ NumPy Array + GPU + Autograd + Deep Learning Features

That’s why modern ML frameworks use tensors everywhere instead of plain matrices or NumPy arrays.

In [14]:
#creating Tensors from Python Lists
import torch

#scalar tensor (0-dimensional tensor)
scalar_tensor = torch.tensor(7)

#vector tensor (1-dimensional tensor)
vector_tensor = torch.tensor([1, 2, 3, 4, 5])

#matrix tensor (2-dimensional tensor)
matrix_tensor = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

#3D tensor (3-dimensional tensor)
tensor_3d = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

In [15]:
print("Scalar Tensor:\n", scalar_tensor)
print("Vector Tensor:\n", vector_tensor)
print("Matrix Tensor:\n", matrix_tensor)

Scalar Tensor:
 tensor(7)
Vector Tensor:
 tensor([1, 2, 3, 4, 5])
Matrix Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [16]:
#making tensors from specific data types

int_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)
long_tensor = torch.tensor([1, 2, 3], dtype=torch.int64)

float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
double_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float64)

print("Integer Tensor:\n", int_tensor.dtype ,"Integer Tensor Size:\n", int_tensor.size())
print("Long Tensor:\n", long_tensor.dtype)
print("Float Tensor:\n", float_tensor.dtype)    
print("Double Tensor:\n", double_tensor.dtype)

Integer Tensor:
 torch.int32 Integer Tensor Size:
 torch.Size([3])
Long Tensor:
 torch.int64
Float Tensor:
 torch.float32
Double Tensor:
 torch.float64


In [17]:
#making tensors with specified data

zeroes_tensor = torch.zeros(0,0)

ones_tensors = torch.ones(2,4)

empty_tensors = torch.empty(2,2)

filled_tensors = torch.full((2,2),43)

print("Zeroes Tensor:\n", zeroes_tensor)
print("Ones Tensor:\n", ones_tensors)
print("Empty Tensor:\n", empty_tensors)
print("Filled Tensor:\n", filled_tensors)



Zeroes Tensor:
 tensor([], size=(0, 0))
Ones Tensor:
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
Empty Tensor:
 tensor([[2.2595e+00, 4.3297e-41],
        [2.2595e+00, 4.3297e-41]])
Filled Tensor:
 tensor([[43, 43],
        [43, 43]])


In [18]:
#Creating sequential tensors

#linear tensor : 5 values evenly spaced between 0 and 10
linear_tensor = torch.linspace(0, 10, steps=5)

#range tensor from 0 to 9
range_tensor = torch.arange(0, 10)

#step tensor from 0 to 10 with step size of 2
step_tensor = torch.arange(0, 10, step=2)

#logspace tensor from 10^0 to 10^3 with 4 steps
logspace_tensor = torch.logspace(0, 3, steps=4)

print("Linear Tensor:\n", linear_tensor)
print("Range Tensor:\n", range_tensor)
print("Step Tensor:\n", step_tensor)
print("Logspace Tensor:\n", logspace_tensor)


#creating random tensors

random_tensor = torch.rand(size=(3,3,4))

print("Random Tensor:\n", random_tensor)


Linear Tensor:
 tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
Range Tensor:
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Step Tensor:
 tensor([0, 2, 4, 6, 8])
Logspace Tensor:
 tensor([   1.,   10.,  100., 1000.])
Random Tensor:
 tensor([[[0.5198, 0.9454, 0.5276, 0.3197],
         [0.3006, 0.6298, 0.2554, 0.1146],
         [0.8789, 0.8289, 0.9470, 0.4512]],

        [[0.1170, 0.7961, 0.7559, 0.0121],
         [0.2719, 0.9104, 0.7233, 0.6840],
         [0.4680, 0.4865, 0.5514, 0.3173]],

        [[0.3547, 0.8804, 0.4484, 0.5195],
         [0.9744, 0.3296, 0.8889, 0.6273],
         [0.9694, 0.0390, 0.7029, 0.2797]]])


In [19]:
'''
Standard Image formats in deep Learning:
- ImageNet format: (batch_size, channels, height, width)(RGB images)
    example: (32, 3, 224, 224) for a batch of 32 RGB images of size 224x224
- CIFAR format: (batch_size, height, width, channels)(RGB images)
    example: (32, 32, 32, 3) for a batch of 32 RGB images of size 32x32
- MNIST format: (batch_size, height, width)(grayscale images)
    example: (32, 28, 28) for a batch of 32 grayscale images of size 28x28
- High Resolution format: (batch_size, channels, height, width)
    example: (32, 3, 1024, 1024) for a batch of 32 RGB images of size 1024x1024
'''

'\nStandard Image formats in deep Learning:\n- ImageNet format: (batch_size, channels, height, width)(RGB images)\n    example: (32, 3, 224, 224) for a batch of 32 RGB images of size 224x224\n- CIFAR format: (batch_size, height, width, channels)(RGB images)\n    example: (32, 32, 32, 3) for a batch of 32 RGB images of size 32x32\n- MNIST format: (batch_size, height, width)(grayscale images)\n    example: (32, 28, 28) for a batch of 32 grayscale images of size 28x28\n- High Resolution format: (batch_size, channels, height, width)\n    example: (32, 3, 1024, 1024) for a batch of 32 RGB images of size 1024x1024\n'

In [20]:
#creating identity matrix

identity_matrix = torch.eye(3)

#creating non square identity matrix
non_square_identity = torch.eye(2, 3)

print("Identity Matrix:\n", identity_matrix)
print("Non-Square Identity Matrix:\n", non_square_identity)


Identity Matrix:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
Non-Square Identity Matrix:
 tensor([[1., 0., 0.],
        [0., 1., 0.]])


In [21]:
#creating diagnonal matrix

#creating matrix from vectors
vectors = torch.tensor([1, 2, 3])
diagonal_matrix = torch.diag(vectors)

#extracting diagonal elements from a matrix
matrix = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
diagonal_elements = torch.diag(matrix)

print("Diagonal Matrix:\n", diagonal_matrix)
print("Diagonal Elements:\n", diagonal_elements)

Diagonal Matrix:
 tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])
Diagonal Elements:
 tensor([1, 5, 9])


In [22]:
float_32_tensor = torch.tensor(
    [1.0, 2.0, 3.0], 
    dtype=None, #default is None which is torch.float32 
    device=None, #default is None which is torch.device('cpu') 
    requires_grad=False, #if True, will record operations on the tensor
)
float_32_tensor.shape , float_32_tensor.dtype , float_32_tensor.device , float_32_tensor.requires_grad

(torch.Size([3]), torch.float32, device(type='cpu'), False)